### ISSUE TITLE
optional destination for tweaked easyconfigs

### ISSUE THREAD

**Issue by dominikborkowski** [easybuilders/easybuild#140]
When using EasyBuild with very useful --try\* options, a new easyconfig is generated in current working directory. It would be great to have ability to specify destination directory for those, to limit clutter.

Thanks!

**Comment by migueldiascosta** [comment]
tweaked easyconfigs go to `os.path.join(tmpdir, 'tweaked_easyconfigs')` since at least https://github.com/easybuilders/easybuild-framework/pull/1059, and `tmpdir` can be specified from the command line.

More recently, the new `--copy-ec` (https://github.com/easybuilders/easybuild-framework/pull/3142) can be combined with `--try-*` (https://github.com/easybuilders/easybuild-framework/pull/3332) to achieve the desired behaviour
