### ISSUE TITLE
2015'B' version for intel/foss in 2.1.x with GCC=4.8.5

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild#145]
re:  https://github.com/hpcugent/easybuild/wiki/Conference-call-notes-20150812

Would it be possible/difficult to distribute a 'B' version of the new foss/intel  'b' toolchains that sticks with GCC 4.8.x?   I'd use it. :)  (and would go less far astray if it was there).

**Comment by JackPerdue** [comment]
BTW... I wouldn't be making anything easier for myself since I already ventured forth with an intel/2015B:

http://www.siliconslick.com/easybuild/ebfiles_repo_cleaned/ada/intel/intel-2015B.eb

and rebuilt GraphViz with a shed load of updated dependencies (almost 50 modules in all including toolchain):

http://www.siliconslick.com/easybuild/ebfiles_repo_cleaned/ada/Graphviz/Graphviz-2.38.0-intel-2015B.eb

Fortunately, I stuck with goolf/1.7.20 for libMesh which only was about 30 modules in all:

http://www.siliconslick.com/easybuild/ebfiles_repo_cleaned/ada/libMesh/libMesh-0.9.4-goolf-1.7.20-Python-2.7.10.eb

though I never did like the "goolf" name.  foss/2015B with GCC 4.8.x would be better. :)

BTW... FWIW, and off topic but for the fact that I decided to remain toolchain neutral, I slapped together the next one for Agisoft's PhotoScanPro software today.  It has need for all kinds of modules (xml/png/zip/etc.), but I left it neutral for now (it mostly uses /usr/lib64).

http://www.siliconslick.com/easybuild/ebfiles_repo_cleaned/ada/PhotoScanPro/PhotoScanPro-1.1.6.eb

It's my favourite... short, sweet, to the point, done.

**Comment by boegel** [comment]
It may sense to define an alternative to `2015b` which is more suited for bioinformatics stuff, although I feel issues with newer compilers should be dealt with/fixed rather than just sticking to an old(er) compiler.

However, naming it `2015B` is a bad idea imho, since it would cause quite a bit of confusion (`b` vs `B` is a small difference, and will result in easy mixup). @JackPerdue: Of course, whichever toolchains you define locally is up to you. I'm talking about toolchains that get defined in the central repo here, with the intention to get them to be used by several sites.

A first alternative that comes to mind is `2015b-GCC-4.8.5`, but that's not exactly pretty. Maybe something along the lines of `2015b-bio`?

**Comment by migueldiascosta** [comment]
assuming this is no longer relevant and closing
