### ISSUE TITLE
Option --minimal-toolchains is active by default

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild#530]
```
$ eb --version
This is EasyBuild 3.9.4.dev0-r7c9e3e5af41717f7a8f6a4617f7be96c4bc99fb5 (framework: 3.9.4.dev0-r7c9e3e5af41717f7a8f6a4617f7be96c4bc99fb5, easyblocks: 3.9.4.dev0-r5f8329b20b86d37524d8aa55c4979a47dc3b75b2) 
```
The build of a package in the intel toolchain results in dependencies being taken from the GCCcore toolchain instead of those already available in the intel toolchain. This is contrary to what is stated in the documentation (https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html) and in `eb -H` where `--minimal-toolchains` is described as `(def False)`

The case at hand concerns `MUMPS-5.1.2-intel-2018a-metis` and `SuiteSparse-5.1.2-intel-2018a-METIS-5.1.0`. Both depend on METIS-5.1.0 and we have `METIS/5.1.0-GCCcore-6.4.0` and `METIS/5.1.0-intel-2018a` available. For instance, the dependencies of MUMPS are defined as 
```
dependencies = [
    ('SCOTCH', '6.0.6'),
    ('METIS', '5.1.0'),
]
```
However, the dependencies in the postprocessed file `reprod/MUMPS-5.1.2-intel-2018a-metis.eb` read
```
dependencies = [
    ('SCOTCH', '6.0.6'),
    ('METIS', '5.1.0', '', ('GCCcore', '6.4.0')),
]
```
Is this change of behavior intended and hence the documentation needs to be updated, or is this a bug?

**Comment by ocaisa** [comment]
I think that documentation just needs some clarification. The default behaviour is still that EB will try to take a dependency with the same toolchain, however if one does not exist it will search through the available subtoolchains to see if it can find a match there (in this case: `intel` -> `iimpi` -> `iccifort` -> `GCCcore`). `--minimal-toolchains` would reverse the order of the search.

In this case `Metis` does not exist with toolchain `intel`, so it resolved the one it could find (`GCCcore`).

**Comment by ocaisa** [comment]
There's a note at https://easybuild.readthedocs.io/en/latest/Manipulating_dependencies.html?highlight=dependency%20resolution#using-minimal-toolchains-for-dependencies that should probably be reproduced there: 
```
Also note that as of v3.0, if no easyconfig exists to resolve a dependency using the default toolchain EasyBuild will search for the dependency using a compatible subtoolchain (the difference being that the search order is from the top of the toolchain hierarchy to the bottom).
```

**Comment by ocaisa** [comment]
PR opened: https://github.com/easybuilders/easybuild/pull/531

**Comment by lexming** [comment]
Ok, so EB only considers packages with an available easyconfig in the repository to fulfill the dependencies. That's what confused me then. Just for clarity, does the resolution of dependencies work according to the following steps (in a broad sense)?

1. Check in the repository of easyconfigs for packages that fulfill a given dependency
2. Check if any of the available options is already installed
3. If dependency is not installed, chose the one in the highest compatible toolchain

Or maybe steps 2 and 3 are switched?

1. Check in the repository of easyconfigs for packages that fulfill a given dependency
2. Chose the package for the dependency in the highest compatible toolchain
3. Install dependency if it is not already installed

In any case, this explains my issue. In our system, `METIS/5.1.0-intel-2018a` is available as a module even though there is no easyconfig for it. I do not know the origin of the module, but probably the toolchain was overwritten with the install command or somebody made a custom easyconfig. Therefore, it is ignored by EB.

Thanks for the quick reply.

**Comment by ocaisa** [comment]
> Ok, so EB only considers packages with an available easyconfig in the repository to fulfill the dependencies.

Unfortunately this a _yes-and-no_ answer, it depends on the module naming scheme you have chosen to use. If you use the default naming scheme it should just pick up the installed module (with the latest EB, this was a [PR relatively recently](https://github.com/easybuilders/easybuild-framework/pull/2698)). If you use, e.g., a hierarchical scheme then the MNS needs the easyconfig to figure out where to find the module in the hierarchy. 

> 
> 1. Check in the repository of easyconfigs for packages that fulfill a given dependency

Yes

> 2. Check if any of the available options is already installed

You have to enable `--use-existing-modules` for that. This forces it to check all the options to see if there is anything at all already available (see [here](https://easybuild.readthedocs.io/en/latest/Manipulating_dependencies.html?highlight=dependency%20resolution#taking-existing-modules-into-account))

> 3. If dependency is not installed, chose the one in the highest compatible toolchain

Yes this is the default (and minimal toolchains would chose the lowest).

> 
> 1. Check in the repository of easyconfigs for packages that fulfill a given dependency
> 2. Chose the package for the dependency in the highest compatible toolchain
> 3. Install dependency if it is not already installed
>

This is the default behaviour.

> In any case, this explains my issue. In our system, `METIS/5.1.0-intel-2018a` is available as a module even though there is no easyconfig for it. I do not know the origin of the module, but probably the toolchain was overwritten with the install command or somebody made a custom easyconfig. Therefore, it is ignored by EB.

You want the first type of behaviour (which is not the default), so you would need to `--use-existing-modules` to tell it to use the installed version (and it will even if there is no easyconfig...as long as your MNS does not require one).

In any case all of your installed easyconfigs get archived into `/my/path/to/ebfiles_repo`, you could include that in your robot search with
```
eb --robot=/my/path/to/ebfiles_repo ...
```
This would work around your problem and is something we always do when developing our software stack (since we have multiple installers and they could all potentially be using custom easyconfigs).

**Comment by lexming** [comment]
This is perfectly clear now. Thanks for the explanation.
