### ISSUE TITLE
xml.etree.ElementTree.ParseError: not well-formed

### ISSUE THREAD

**Issue by alchemroz** [easybuilders/easybuild#621]
Hello,
         I installed successfully easybuild 4.2.0 on a centos 8 with pip 3.6. Everything went smooth until the installation of

eb Python-3.7.2-GCCcore-8.2.0.eb --robot

I attached the log 
[easybuild-vdqc5b6i.log](https://github.com/easybuilders/easybuild/files/4594100/easybuild-vdqc5b6i.log)

Thanks for the help

**Comment by boegel** [comment]
@alchemroz This problem is caused by a change made to PyPI, where specific version of Python packages can now be tagged as "yanked". EasyBuild trips over the `data-yanked` attribute that is used to indicate yanked releases.

We've been in touch with the PyPI maintainers to try and see if the change that broke the auto-downloading of Python packages in EasyBuild can be tweak to avoid existing EasyBuild releases breaking, see https://github.com/pypa/warehouse/issues/7886 .

Meanwhile, we have implemented a workaround for this problem in https://github.com/easybuilders/easybuild-framework/pull/3303, it shouldn't be very difficult to patch your existing EasyBuild installation if you want to, see https://github.com/easybuilders/easybuild-framework/pull/3303/files#diff-80e271b8fd31ff4cff170771374ccbe2 .

A proper fix, where we avoid using the `xml.etree.ElementTree` from the Python standard library that trigger the failure, is implemented in https://github.com/easybuilders/easybuild-framework/pull/3329, and will also be included in EasyBuild v4.2.1 .
