### ISSUE TITLE
install a software not on default path

### ISSUE THREAD

**Issue by farzad685** [easybuilders/easybuild#651]
I am installed easybuild-4.3.0 and I want to install a software in my desired path. I enter this command in my desired path 
farzad@farzad-faghihi:~/Downloads$ `eb GCC-7.5.0.eb --robot`
but I received the error ```
== temporary log file in case of crash /tmp/eb-6siq2jbc/easybuild-kg9b9kiy.log
ERROR: Can't find path /home/farzad/Downloads/GCC-7.5.0.eb
```
Is there anyone help me?
thanks a lot.
(gcc-7.5.0 is just for example.)

**Comment by pescobar** [comment]
Hi @farzad685 

Easybuild doesn't provide any easyconfig named `GCC-7.5.0.eb` and it's trying to search for it in your current directory but it triggers and error because it cannot find it.

I would recommend you to first try a test installation as this example described in the docs which shows how to search for available easyconfigs and install them: https://easybuild.readthedocs.io/en/latest/Typical_workflow_example_with_WRF.html

Once you install your first example you can apply the same steps to install other easyconfigs. Of course it's recommended that you also read the basics concepts about easybuild in the official docs: https://easybuild.readthedocs.io/en/latest/

**Comment by farzad685** [comment]
Hi @pescobar .thanks for your answer.
But my main issue is not about the software exists or not. Software like WRF that exists, I do not want to install it on this path /home/example/.local/easybuild/software/EasyBuild/4.1.1/easybuild/easyconfigs for example I want to install on /home/username/model/libraries.

**Comment by pescobar** [comment]
Check the docs
 https://easybuild.readthedocs.io/en/latest/Configuration.html#installpath

**Comment by farzad685** [comment]
@pescobar . although there is not an example to do in the docs, I thank you a lot because at least now I know I should look what for.
