### ISSUE TITLE
Best way to add external product

### ISSUE THREAD

**Issue by adrien-cotte** [easybuilders/easybuild#729]
Hello,

I am using EasyBuild since 2016, so thank you for this awesome project!

I need to add an external product which is managed by a very specific community.
I do not have write permission on their files so EasyBuild fails at the permissions step.

I use a Bundle block to avoid build/install steps:

```
easyblock = 'Bundle'
name = 'toto'
version = '0.1.0'
homepage = ''
description = ''
toolchain = SYSTEM

keeppreviousinstall = True
skipsteps = ['permissions']

sanity_check_paths = {
    'files': ['bin/toto'],
    'dirs': ['bin', 'lib'],
}
```

Yes, basically I could just use `eb --module-only` but I would like a pure easyconfig file solution in order to have one only robot script with unique `eb <my_opts>` call for each software.

The `skipsteps = ['permissions']` does not work, so I have implemented an easyblock `ModuleOnly` which has:
```
def permissions_step(self):
    pass
```

What is the best way to add an external product without touch it?

Many thanks,
Adrien

**Comment by ocaisa** [comment]
I don't see an elegant solution here as this is kind of against the principle of an easyconfig since what is inside the directory is essentially a moving target.

Do you plan on using this as a dependency for something else? The [idea of external dependencies is already in EB](https://docs.easybuild.io/en/latest/Using_external_modules.html), but you would still create the module file yourself. We've also had the case in the past that we wrap around system compilers and system MPI installations, but those cases are explicitly handled in specific easyblocks (https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/generic/systemmpi.py for example). A custom easyblock is probably the way to go.

**Comment by adrien-cotte** [comment]
Many thanks, have a nice day.

**Comment by adrien-cotte** [comment]
Maybe it could be useful for someone.
I finally export this:

export EASYBUILD_MAX_FAIL_RATIO_ADJUST_PERMISSIONS=1

This is equivalent to skip 'permissions' step.
