### ISSUE TITLE
Problems building specific WPS version (WRF Preprocessing System )

### ISSUE THREAD

**Issue by kabm1979** [easybuilders/easybuild#807]
I just installed WRF-3.9.1.1 sucessfully (using WRF-3.9.1.1-foss-2020b-dmpar.eb available with EasyBuild 4.5.5). But I need (as requirement from researchers-users) WPS 3.9.1 for pre-processing data. However, there is no easyconfig file for WPS-3.9.1.

There are significative differences between 3.9.1 versions and newer 4.x versions. Therefore, I chose an older version ( WPS-3.8.0-intel-2016a-dmpar.eb) and I changed toolchain (foss-2020b) and dependencies. When I executed new easyconfig file I got an error in testing step:

`
== configuring...
== ... (took 2 secs)`
`
== building...
== ... (took 43 secs)`
`
== testing...
== ... (took 4 mins 52 secs)`
`
== FAILED: Installation ended unsuccessfully (build directory: /dae/apps/easybuild/modulefiles/easybuild/software/WPS/3.8.0-foss-2020b-dmpar): build failed (first 300 chars): cmd "mpirun -n 1 /dae/apps/easybuild/modulefiles/easybuild/software/WPS/3.8.0-foss-2020b-dmpar/WPS/geogrid.exe" exited with exit code 132 and output:
mpirun was unable to launch the specified application as it could not acces (took 5 mins 45 secs)`
`
== Results of the build can be found in the log file(s) /tmp/eb-BUydHJ/easybuild-WPS-3.8.0-20220623.150942.ErgXf.log
ERROR: Build of /home/administrador/WPS-3.8.0-foss-2020b-dmpar.eb failed (err: 'build failed (first 300 chars): cmd "mpirun -n 1 /dae/apps/easybuild/modulefiles/easybuild/software/WPS/3.8.0-foss-2020b-dmpar/WPS/geogrid.exe" exited with exit code 132 and output:\n--------------------------------------------------------------------------\nmpirun was unable to launch the specified application as it could not acces')
`

Binaries were not created (like geogrid.exe), despite building step is completed..
What can I do to complete WRF installation??
Attached the easyconfig file generated...

Thanks, in advanced for support of this great Easybuild Team
[WPS-3.8.0-foss-2020b-dmpar.zip](https://github.com/easybuilders/easybuild/files/8970404/WPS-3.8.0-foss-2020b-dmpar.zip)

**Comment by boegel** [comment]
@kabm1979 The problem is that GCC 10.x has become a bit more strict, and that's causing compiler errors for this old Fortran code:

```
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
```

There's a relatively easy workaround though: you can use the `-fallow-argument-mismatch` compiler option to make GCC 10.x accept this code; see also https://www.gnu.org/software/gcc/gcc-10/porting_to.html .

For WPS specifically, this is currently not entirely trivial though. To make it a bit easier, I have made a small enhancement to the WPS easyblock so it picks up on `prebuildopts` if that's set in the WPS easyconfig file being installed, see https://github.com/easybuilders/easybuild-easyblocks/pull/2754 .

Next to this, I also had to add two small patch files (taken from https://github.com/wrf-model/WPS/pull/119 and https://github.com/wrf-model/WPS/pull/50) to fix compilation problems, and make sure that the netCDF-Fortran include files are available (to ensure that `netcdf.mod` is found) by injecting an additional `-I` option.

I've opened a pull request for WPS 3.9.1 that includes all necessary changes, see https://github.com/easybuilders/easybuild-easyconfigs/pull/15769 .

To install this with EasyBuild v4.5.5, you can use:

```
eb --from-pr 15769 --include-easyblocks-from-pr 2754
```
