### ISSUE TITLE
libarchive wchart_t error.

### ISSUE THREAD

**Issue by ismailguzel** [easybuilders/easybuild#900]
Installing libarchive-3.7.2 with 

```
eb libarchive-3.7.2-GCCcore-13.2.0.eb -r
```
It occurs the following error in confguration steps

```
......
checking for wchar_t... yes
checking size of wchar_t... configure: error: in `.../easybuild/build/libarchive/3.7.2/GCCcore-13.2.0/libarchive-3.7.2':
configure: error: cannot compute sizeof (wchar_t)
```

**Comment by ocaisa** [comment]
I see this in https://github.com/NixOS/nixpkgs/issues/5608, are you installing on MacOS? EasyBuild is only really supported for Linux so if you are, you are likely to run into a lot of issues.

**Comment by ocaisa** [comment]
If you are interested in running EasyBuild software on MacOS, I suggest you take a look at the EESSI project (https://www.eessi.io/docs/, and in particular https://www.eessi.io/docs/getting_access/eessi_limactl). `foss/2023b` is available there and you can also easily extend the installations using the [`EESSI-extend` module](https://www.eessi.io/docs/available_software/detail/EESSI-extend/)

**Comment by ismailguzel** [comment]
I am not installing on MacOS. I am trying to install it on HPC cluster with Rocky-Linux-9

**Comment by ocaisa** [comment]
Something is really fishy here, this same error is discussed in detail in https://github.com/libarchive/libarchive/issues/728 , but again the problem is macOS. You may need to look deeper into the configuration output and see if it is picking up unexpected things from the host, that means also inspecting the `config.log` file in the build directory to see what command it is trying to run and why it is failing.

**Comment by ismailguzel** [comment]
[config.log](https://github.com/user-attachments/files/16908769/config.log)
Here is my config.log.  I examined it  but didnt solve issue.

**Comment by ocaisa** [comment]
The error is in there alright:
```
...
configure:18419: checking size of wchar_t
configure:18425: gcc -o conftest -O2 -ftree-vectorize -march=native -fno-math-errno -Wall -Wformat -Wformat-security -ffunction-sections -fdata-sections -I/arf/sw/comp/easybuild/software/OpenSSL/1.1/include -I/arf/sw/comp/easybuild/software/XZ/5.4.4-GCCcore-13.2.0/include -I/arf/sw/comp/easybuild/software/zlib/1.2.13-GCCcore-13.2.0/include -I/arf/sw/comp/easybuild/software/binutils/2.40-GCCcore-13.2.0/include -I/arf/sw/comp/python/miniconda3/include/libxml2 -I/arf/sw/comp/python/miniconda3/include  -L/arf/sw/comp/easybuild/software/OpenSSL/1.1/lib64 -L/arf/sw/comp/easybuild/software/OpenSSL/1.1/lib -L/arf/sw/comp/easybuild/software/XZ/5.4.4-GCCcore-13.2.0/lib64 -L/arf/sw/comp/easybuild/software/XZ/5.4.4-GCCcore-13.2.0/lib -L/arf/sw/comp/easybuild/software/zlib/1.2.13-GCCcore-13.2.0/lib64 -L/arf/sw/comp/easybuild/software/zlib/1.2.13-GCCcore-13.2.0/lib -L/arf/sw/comp/easybuild/software/binutils/2.40-GCCcore-13.2.0/lib64 -L/arf/sw/comp/easybuild/software/binutils/2.40-GCCcore-13.2.0/lib -L/arf/sw/comp/easybuild/software/GCCcore/13.2.0/lib64 -L/arf/sw/comp/easybuild/software/GCCcore/13.2.0/lib conftest.c -llzma -lzstd -llz4 -lbz2 -lz -lm -lpthread -L/arf/sw/comp/python/miniconda3/lib -lxml2  >&5
configure:18425: $? = 0
configure:18425: ./conftest
./conftest: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
configure:18425: $? = 127
...
```
So the problem is you have no available `bzip2`, this seems to be missing from the dependencies of `libarchive` Try changing that to:
```python
dependencies = [
    ('zlib', '1.2.13'),
    ('bzip2', '1.0.8'),
    ('XZ', '5.4.4'),
    ('OpenSSL', '1.1', '', SYSTEM),
]
```

(Side note, I don't particularly like seeing the `miniconda` paths in your configuration, `conda` can do a lot of invasive stuff that may ultimately affect builds. I would, for example, suspect it in your previous issue #899)

**Comment by ismailguzel** [comment]
Yes, I used conda platform. Your suggestion `('bzip2', '1.0.8'),` and `('libiconv', '1.17'),` solved the problem. 

```
dependencies = [
    ('zlib', '1.2.13'),
    ('bzip2', '1.0.8'),
    ('libiconv', '1.17'),
    ('XZ', '5.4.4'),
    ('OpenSSL', '1.1', '', SYSTEM),
]
```


But, I will reinstall easybuild without conda and try to install all programs. 

Thank you so much for quick and efficient helps.

**Comment by ocaisa** [comment]
These really probably should be dependencies of `libarchive`, but it may only be the case that they are required in certain cases. It's hard to tell unless you dig into the details of the configuration step.

If you try without conda, you will probably have to rebuild all the existing software (the gcc from conda rather than the OS will, I suspect, have been used to start bootstrapping).
